Yet another cleanup PR (#96)
* Add node Docker scripts

* Fix error when compute zone is set before project

Problem:
CI fails with the error:

configure compute zone...
Updated property [compute/zone].
ERROR: (gcloud.config.set) The required property [project] is not currently set.
It can be set on a per-command basis by re-running your command with the [--project] flag.

You may set it for your current workspace by running:

  $ gcloud config set project VALUE

or it can be set temporarily by the environment variable [CLOUDSDK_CORE_PROJECT]

Cause:
GCloud SDK requires that the project be set before the compute zone is set.

Fix:
Set the project before the compute zone.

* Switch Pull Approve team to Arepa

* Allow hub to be ran without installing this repo as a submodule

* Allow setup_volumes.sh to be ran without installing this repo as a submodule

* Fix Docker volumes are always created

Problem:
Docker volumes are always being created, even when they already exist.

Fix:
Fix and simplify the logic that checks if the volume exists.

* Fix Docker volumes are assumed to be directories

Problem:
When creating volumes, if a valid ~/.gitconfig already exists, the script errors our with the message:

~/.gitconfig already exists, but it is not a directory

This is problematic, because ~/.gitconfig is supposed to be a file.

Cause:
The createDockerVolume function of setup_nfs_functions.sh is assuming that all volumes are directories. This is not the case.

Fix:
Improve the function logic to ensure the appropriate disk member exists, be it a directory or a file.

* Move new functions to lib scripts

* Add local vars for method arguments